// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3FNLmZSLGymTuWC6kYA5b2SLGwN_m2vQ',
    appId: '1:512680544239:web:f81167e2c801da3347d81a',
    messagingSenderId: '512680544239',
    projectId: 'air-raid-9a79a',
    authDomain: 'air-raid-9a79a.firebaseapp.com',
    databaseURL:
        'https://air-raid-9a79a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-raid-9a79a.firebasestorage.app',
    measurementId: 'G-VQ1FLECC5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDarlTl9zO6HDfrapopeAEhIRvbhsJgRvY',
    appId: '1:512680544239:android:b4a7ec7227311e2447d81a',
    messagingSenderId: '512680544239',
    projectId: 'air-raid-9a79a',
    databaseURL:
        'https://air-raid-9a79a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-raid-9a79a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3FNLmZSLGymTuWC6kYA5b2SLGwN_m2vQ',
    appId: '1:512680544239:web:843ef29977248fff47d81a',
    messagingSenderId: '512680544239',
    projectId: 'air-raid-9a79a',
    authDomain: 'air-raid-9a79a.firebaseapp.com',
    databaseURL:
        'https://air-raid-9a79a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-raid-9a79a.firebasestorage.app',
    measurementId: 'G-BNWSF2BKGP',
  );
}
